IF OBJECT_ID('UTILISATEUR', 'U') IS NOT NULL 
  DROP TABLE UTILISATEUR; 

CREATE TABLE UTILISATEUR (
	IDU DECIMAL(10) IDENTITY(1,1) NOT NULL,
	LOGIN NVARCHAR(40) NOT NULL,
	PASSWD NVARCHAR(100) NOT NULL,
	NoCli decimal(10, 0),
	CONSTRAINT PK_UTILISATEUR PRIMARY KEY (IDU),
	CONSTRAINT FK_CLIENT FOREIGN KEY (NoCli)  REFERENCES CLIENT (NoCli) 
)

BEGIN TRANSACTION;
-- lulu38000
INSERT INTO UTILISATEUR (LOGIN, PASSWD, NoCli) VALUES ('lulu', 'CLZHuGtf0Ks8BFBfJGxDGw==', 100);
-- phiphi31000
INSERT INTO UTILISATEUR (LOGIN, PASSWD, NoCli) VALUES ('phiphi', 'nuSo6y2113P/wUQ4y1kD6w==', 99);
COMMIT TRANSACTION;