-- Source : https://www.mssqltips.com/sqlservertip/4037/storing-passwords-in-a-secure-way-in-a-sql-server-database/

IF OBJECT_ID('UTILISATEUR', 'U') IS NOT NULL 
  DROP TABLE UTILISATEUR; 

CREATE TABLE UTILISATEUR (
	IDU DECIMAL(10) IDENTITY(1,1) NOT NULL,
	LOGIN NVARCHAR(40) NOT NULL,
	PASSWD NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_UTILISATEUR PRIMARY KEY (IDU)
)

BEGIN TRANSACTION;
-- lulu38000
INSERT INTO UTILISATEUR (LOGIN, PASSWD) VALUES ('lulu', 'CLZHuGtf0Ks8BFBfJGxDGw==');
-- phiphi31000
INSERT INTO UTILISATEUR (LOGIN, PASSWD) VALUES ('phiphi', 'nuSo6y2113P/wUQ4y1kD6w==');
COMMIT TRANSACTION;

