-- Source : https://www.mssqltips.com/sqlservertip/4037/storing-passwords-in-a-secure-way-in-a-sql-server-database/

CREATE TABLE UTILISATEUR (
	IDU DECIMAL(10) IDENTITY(1,1) NOT NULL,
	LOGIN NVARCHAR(40) NOT NULL,
	PASSWD NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_UTILISATEUR PRIMARY KEY (IDU)
)

BEGIN TRANSACTION;
INSERT INTO UTILISATEUR (LOGIN, PASSWD) VALUES ('lulu', 'lulu38000');
INSERT INTO UTILISATEUR (LOGIN, PASSWD) VALUES ('phiphi', 'phiphi31000');
COMMIT TRANSACTION;

